[tool.poetry]
name = "libb-cmd"
version = "0.1.0"
description = ""
authors = ["bissli <bissli@xyz.com>"]
readme = "README.md"
packages = [{ include = "cmdline", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"

applog = { git = "https://github.com/bissli/applog" }
opendate = "^0.1.39"

# == test
pytest = { version = "*", optional = true }
pytest-runner = { version = "*", optional = true }
wrapt = { version = "*", optional = true }

[tool.poetry.extras]
test = [
  "pytest",
  "pytest-runner",
  "wrapt",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
